import fs from "node:fs";
import path from "node:path";
import { loadEnv } from "./lib/env.mjs";
loadEnv(".env");
const siteId = "petgearbench";
const outDir = path.join(process.cwd(), "reports");
fs.mkdirSync(outDir, { recursive: true });
const report = ["# Pet Gear Bench Weekly Affiliate Pulse", "", `Generated: ${new Date().toISOString()}`, "", "## Local baseline", "- Guides published: 5", "- Curated ASINs: 6", "- Amazon tag: abbeybench-20", "", "## Next actions", "- Refresh one money page 30 to 45 days before the next seasonal peak.", "- Add one comparison page and one tutorial page that internally link to the highest-intent guide.", "- Review outbound click and subscriber data before changing the content calendar."].join("\n");
const file = path.join(outDir, `weekly-pulse-${new Date().toISOString().slice(0,10)}.md`);
fs.writeFileSync(file, report);
console.log(file);
